### ISSUE TITLE
OMIX Firmware PLS, X600 4GB, 64GB, UI Version 12.1.0

### ISSUE THREAD

**Issue by Alikpro121** [omixmobile/firmware#3]
X600 4GB RAM, 64GB, S.X600.20230309.V12.1.0
PLS

**Comment by zenlty** [comment]
> X600 4GB RAM, 64GB, S.X600.20230309.V12.1.0 PLS

You can check it from [this link](https://github.com/omixmobile/firmware/releases/tag/V12.1.0_X600_T2202)
